Mathematical/prime-sieve.cpp

This commit adds a naive implementation of the prime sieve that
finds prime numbers in O(loglogN) time complexity and O(N) space
complexity, also known as The Sieve of Eratosthenes.
In response to: https://github.com/Iltwats/hacktoberfest/pull/2#issuecomment-700857325
Also, a word of advice: [Documentation fixes are contributions *too*](https://opensource.guide/how-to-contribute/#you-dont-have-to-contribute-code).

Math: Add Prime Sieve

---

client_file.py
server_file.py

the porgram client_file and server_file useful for transfering files from 1 device to another

Socket Programing

---

Reverse a number.py

To reverse the order of any 4 or more digit number

Create Reverse a number.py

---

HeapSort1.cpp

HeapSort1.cpp

---

Mathematical/catalan-numbers.py

Added catalan numbers algorithm in python in the Mathematical file

Added catalan numbers algorithm in python

---

Non-Alogrithmic/gpa_calc.py

Issue #11 solved and  #12 partially solved.
Test Case mentioned given as sample input.

Basic Implementation of a general purpose GPA Calc added

---

Mathematical/Number guessing game.py

Create Number guessing game.py

---

Stack/ParenthesisChecker.cpp
Stack/StackImplementation.cpp

Added in stack folder 
ParenthesisChecker.cpp and StackImplementation.cpp resolving the issue #26

Parenthesis checker and Stack Implementation in C++

---

Dynamic-Programming/Rodcut.cpp

Rod cutting problem is a fundamental problem in dynamic programming. So I added the code for it in C++.

Added the rodcutting problem

---

Dynamic-Programming/sizeofarray.cpp
String/revrstring.cpp

reverse function by swapping characters

---

Dynamic-Programming/maximumContiguousSubarraySum.cpp

Added Maximum Contiguous Subarray Sum Algorithm (Kadane's Algorithm)

Add maximumContiguousSubarraySum.cpp

---

Sorting/CountingSort.c

This Algorithm sorts the given sequence of non-negative integers numbers in O(n) time where n is the size of the sequence. The only thing that it demands is the largest integer in the sequence. if the largest number is k then its space complexity is O(k+n)

Added CountingSort.c

---

Queue/Queue using two stacks .cpp

Implement Queue using Stacks

---

Stack/InfixTo Postfix.cpp
Stack/TwoStackSingleArray.cpp

Implemented two stacks in a single array using c++

Created TwoStacksSingleArray

---

ML/simple_linear_regression.py

Add an implementation of my awesome algorithm in python that is simple linear regression.

Added simple linear regression in python

---

String/changeToLowerCase.py
String/changeToUpperCase.py
String/isPalindrome.cpp
String/toLower.cpp

Hey there,
I hope you merge these cpp files :')
P.S. I also made some corrections.

Adding isPalindrome.cpp in String

---

Searching/jump-search.cpp

I have included the explanation as requested.

Solution for jump search

---

String/create_substring.cpp

Addding a create_substring function without using its inbuilt feature

---

String/implementing_strcat.cpp

Adding implementing_strcat.cpp without using strcat inbuilt 

---

Graph/bfs.cpp
Graph/dfs.cpp

Made the graphs folder and added bfs, dfs to start with. Check and accept the pull request

added bfs and dfs

---

Mathematical/Pascal's Triangle in C++ Java Python/pascal's traingle in C++.cpp
Mathematical/Pascal's Triangle in C++ Java Python/pascal's triangle in java.java
Mathematical/Pascal's Triangle in C++ Java Python/pascal's triangle in python.py

Added a folder named Pascal's Triangle in which implementation is done using C++, Java, and Python.
Issue #8 
@Iltwats I have updated Pascal's Triangle in the Mathematical folder. 
Kindly look into the changes. :)

Added Pascal's Triangle in C++ Java Python

---

Searching/pivoted_binary_search.cpp

Here's an algorithm to search for an element in a sorted but rotated array using binary search...Happy Hacking!

Added Pivoted Binary search algorithm

---

Graph/Dijkstras.cpp
Searching/pivoted_binary_search.cpp

Dijkstras algorithm

---

Sorting/Gnome-Sort.cpp
Sorting/Gnome-Sort.py

I have added implementation of Gnome sort in python and c++ in Sorting folder.
Issue #18 
Please take a look into it and revert me back if there are any changes to be made.

Added implementation of Gnome Sort in Python and C++

---

Sorting/menu-driven-SortingImplementation.cpp

This program sorts a vector in increasing order by using insertion sort , bubble sort , selection sort methods based on the choice given by the user

Menu Driven Sorting Implementation

---

Dynamic-Programming/CoinChange.cpp

Find minimum number of coins that add up to given money using Dynamic Programming.

Find minimum number of coins that add up to given money 

---

Dynamic-Programming/LongestPalindromicSubsequence.cpp

This program will print the length of the longest palindromic subsequence in a given string using dynamic programming.

Added LongestPalindromicSubsequence.cpp

---

castle.py

an interactive story mode game made using python

Added a python game

---

Backtracking/Sudoku.cpp

This program will solve a sudoku, if valid. Else return invalid sudoku.
Note: I could not find a correct folder to put the program in, so I felt the need of and created a folder for backtracking related problems.

Added Sudoku.cpp

---

Greedy/AssigningMiceToHoles.java

Issue #89 Assigning Mice To Holes problem added

Added AssigningMiceToHoles.java

---

Searching/UnboundedBinarySearch.java

Added implementation of Unbounded Binary Search in Java language

[Issue#22] Add Unbounded Binary Search implementation in Java

---

Graph/Kruskal.cpp

This program will find the minimum spanning tree of a weighted undirected graph using Kruskal's algorithm as well as print its length.
Solves #56 partially.

added Kruskal.cpp

---

Greedy/minimumSwapsForBracketBalancing.cpp

Added Minimum Swaps For Bracket Balancing in C++

---

String/StringPermutation.java

Input: Man
Output: man 	Man     mAn	  MAn	maN	MaN	mAN	MAN

Added StringPermutation problem

---

Mathematical/monty-hall.cpp

Monty hall problem added in c++ with a simulation of 10000 numbers, saved in the Mathematical section.
Monty Hall problem is a theory that suggests that out of 3 doors with 1 car and two goats, the host lets you choose a mystery door and then the host himself opens a door with one goat. Then the host asks if you want to switch your choice. 
The theory suggests that it is always a good idea to switch because then the probability of you winning becomes 2/3.
The program takes a maximum of 10000 cases by default and simulates each time and randomly chooses a door. If the door has a prize behind it and it was switched, a number is incremented. If not, the original door's number is incremented. 
The simulation shows the final output of the winning scenarios.

Monty hall problem added in c++

---

Stack/StackImplementation_C.c

I've implemented the above said functions into a stack of numbers using C

Stack Implementation using C

---

ML/Uniform_Cost_Search.py

This algorithm is used as a base for the famous algorithm A* search which is based on heuristics and ucs, to find the optimal path in the graph, also a variant of Djkstra's Algorithm.
Hoping to merge for Hactoberfest-2020 !!
Also, mark hacktoberfest-2020 label if feasible, i am beginner to github.

Added Uniform Cost Search

---

Graph/kruskal.java

HacktoberFest 2021 Pull Request

Add an implementation of my Kruskal's algorithm in Java

---

String/maximumSubArrayXOR.java

Added java code for maximum subarray XOR in a given array.

JAVA code for maximum subarray XOR in a given array

---

Some_Random/Dice_Simulator.py

A random dice simulator in python.

Added random Dice Simulator in python

---

Sorting/bubble sort.swift

Added bubble sort algorithm written in swift language

Added bubble sort algorithm

---

DataStructures/String/check_divisibilty_of_large_number.py

This is my solution to number 16: To check divisibility of large number by 999

To check divisibility of large number by 999, Python

---

DataStructures/Array/helloworld.py

Reverts The-Streamliners/Data-Structures-and-Algorithms#269

Revert "Created Helloworld.py"
